import {useEffect,useRef} from 'react';
export function ResultBests({bests,newBest,label,accuracy}) {
 if(!bests)return null;
 return <div className="result-bests">{newBest&&<span className="new-best" aria-live="polite" role="status">NEW BEST</span>}<p>BEST SCORE {bests.score} · BEST {label} {bests.count}{accuracy&&bests.accuracy!==null?' · BEST ACCURACY '+bests.accuracy.toFixed(1)+'%':''}</p></div>;
}
export function GameHUD({round,title,introduction,label,accuracy,onSkip}) {
 const action=useRef(null),g=round.display;useEffect(()=>{if(g.phase==='results'||g.paused)action.current?.focus({preventScroll:true});},[g.phase,g.paused]);
 return <>{g.phase==='playing'&&<div className="slash-hud" aria-label={title+' session'}><div className="hud-metrics"><div><span>SCORE</span><strong aria-label="Score">{g.score||0}</strong></div><div><span>{label}</span><strong aria-label={label}>{g.count}</strong></div></div><time aria-label="Time remaining">{Math.floor(g.seconds/60)}:{String(g.seconds%60).padStart(2,'0')}</time></div>}{g.phase==='playing'&&!g.paused&&onSkip&&<button className="shape-skip" onClick={onSkip}>SKIP</button>}{(g.phase!=='playing'||g.paused)&&<section className="slash-game-overlay" aria-label={title+' game'}>{g.paused?<><h2>Paused</h2><p>{round.canPlay?'Continue when you’re ready.':'Enable your camera or use mouse / touch to continue.'}</p><button ref={action} className="enter" disabled={!round.canPlay} onClick={round.resume}>RESUME</button></>:g.phase==='countdown'?<div className="slash-countdown" aria-label="Starting in" aria-live="polite">{g.countdown}</div>:<><h2>{title}</h2><p>{g.phase==='results'?g.count+' '+label:introduction}</p>{g.phase==='results'&&<><p aria-label="Final score">{g.score||0} POINTS</p>{accuracy!=null&&<p>{accuracy.toFixed(1)}% AVERAGE ACCURACY</p>}<ResultBests bests={g.bests} newBest={g.newBest} label={label} accuracy={accuracy!=null}/></>}<button ref={action} className="enter" disabled={!round.canPlay} onClick={round.start}>{g.phase==='results'?'PLAY AGAIN':'START'}</button></>}</section>}</>;
}
