import {useEffect,useRef,useState} from 'react';
import {createRoundClock} from './roundClock';
export function useRound({duration,mouseMode,cameraReady,videoRef,trackingError,onReset}) {
 const [clock]=useState(()=>createRoundClock(duration));const stateRef=useRef(clock.tick(0));const [display,setDisplay]=useState(stateRef.current);const epoch=useRef(0);const session=useRef(0);const settings=useRef(null);settings.current={mouseMode,cameraReady,videoRef,trackingError,onReset};
 const available=()=>{const s=settings.current,v=s.videoRef?.current;return s.mouseMode||!!(s.cameraReady&&!s.trackingError&&v?.readyState>=2&&!v.paused&&!v.ended);};
 const publish=state=>{const old=stateRef.current;stateRef.current=state;if(['phase','paused','seconds','countdown','count','pauseReason'].some(k=>old[k]!==state[k]))setDisplay(state);};
 useEffect(()=>{let raf;const pause=reason=>{epoch.current++;settings.current.onReset?.(false);publish(clock.pause(performance.now(),reason));};const visibility=()=>{if(document.hidden)pause('visibility');};document.addEventListener('visibilitychange',visibility);const tick=now=>{let state=clock.tick(now);if(!available()&&(state.phase==='countdown'||state.phase==='playing')&&!state.paused){pause('camera');state=clock.tick(now);}publish(state);raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(raf);document.removeEventListener('visibilitychange',visibility);clock.reset();epoch.current++;};},[clock]);
 return {clock,stateRef,display,epoch,session,canPlay:available(),start(){const state=clock.tick(performance.now());if(document.hidden||!available()||!['ready','results'].includes(state.phase))return;epoch.current++;session.current++;settings.current.onReset?.(true);publish(clock.start(performance.now()));},resume(){if(document.hidden||!available())return;epoch.current++;settings.current.onReset?.(false);publish(clock.resume(performance.now()));},hit(n=1){publish(clock.addHits(n,performance.now()));}};
}
