import {test,expect} from '@playwright/test';
test('webcam tracing counts a right-to-left line and a clockwise circle from the side, then advances',async({page})=>{
 await page.addInitScript(()=>{let offset=0;const now=performance.now.bind(performance),raf=requestAnimationFrame.bind(window);performance.now=()=>now()+offset;window.requestAnimationFrame=f=>raf(t=>f(t+offset));window.traceAdvance=s=>offset+=s*1000;
 window.tracePose={x:.5,y:.5};navigator.mediaDevices.getUserMedia=async()=>{const c=document.createElement('canvas');c.width=640;c.height=480;let id;const paint=()=>{c.getContext('2d').fillRect(0,0,640,480);id=requestAnimationFrame(paint);};paint();const stream=c.captureStream(30);stream.getVideoTracks()[0].addEventListener('ended',()=>cancelAnimationFrame(id));return stream;};
 window.Worker=class{postMessage(d){if(d.type==='init')queueMicrotask(()=>this.onmessage?.({data:{type:'ready'}}));if(d.type==='frame'){d.frame.close();const p=window.tracePose,x=(p.x*innerWidth-(innerWidth-innerHeight*4/3)/2)/(innerHeight*4/3),lm=Array.from({length:21},()=>({x:1-x,y:p.y+.12,z:0}));lm[8]={x:1-x,y:p.y,z:0};queueMicrotask(()=>this.onmessage?.({data:{type:'hand',landmarks:lm,timestamp:d.timestamp,sourceWidth:640,sourceHeight:480}}));}}terminate(){this.onmessage=null;}};});
 await page.goto('/?debugTrace');await page.getByRole('button',{name:'FLOW',exact:true}).click();await page.getByRole('button',{name:'ENABLE CAMERA',exact:true}).click();await page.getByRole('button',{name:'START',exact:true}).click();await page.evaluate(()=>window.traceAdvance(3));await expect(page.getByLabel('Time remaining')).toBeVisible();
 const trace=async points=>{for(let i=0;i<points.length;i+=2){await page.evaluate(p=>window.tracePose=p,points[i]);await page.waitForTimeout(70);}await page.evaluate(p=>window.tracePose=p,points.at(-1));await page.waitForTimeout(150);};
 const line=await page.evaluate(()=>window.__lumenTrace.target());await trace([...line].reverse());await expect(page.getByLabel('SHAPES',{exact:true})).toHaveText('1');await expect(page.getByLabel('Score',{exact:true})).not.toHaveText('0');await page.waitForTimeout(700);
 const circle=await page.evaluate(()=>window.__lumenTrace.target());expect(circle).not.toEqual(line);const loop=circle.slice(0,-1),rotated=[...loop.slice(25),...loop.slice(0,25),loop[25]];await trace([...rotated].reverse());await expect(page.getByLabel('SHAPES',{exact:true})).toHaveText('2');await page.waitForTimeout(700);expect(await page.evaluate(()=>window.__lumenTrace.target())).not.toEqual(circle);
});