import {test,expect} from '@playwright/test';import fs from 'node:fs';
const poses=JSON.parse(fs.readFileSync(new URL('../fixtures/gesture-landmarks.json',import.meta.url)));
test('LaunchMode separates recorded open/closed grab poses from pointing creation',async({page})=>{
 await page.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;window.createdInstances=0;HTMLCanvasElement.prototype.getContext=function(type,...args){const gl=original.call(this,type,...args);if(gl&&type==='webgl2'&&this.closest('.launch-artwork')){const draw=gl.drawElementsInstanced.bind(gl);gl.drawElementsInstanced=(...args)=>{window.createdInstances=args[4];return draw(...args);};}return gl;};});
 await page.goto('/');const result=await page.evaluate(async poses=>{
 const React=await import('/node_modules/.vite/deps/react.js'),ReactDOM=await import('/node_modules/.vite/deps/react-dom_client.js'),{LaunchMode}=await import('/src/modes/LaunchMode.jsx'),{updateHand}=await import('/src/tracking/handPointer.js');const host=document.createElement('div');host.style.cssText='position:absolute;inset:0';document.body.append(host);const root=(ReactDOM.createRoot||ReactDOM.default.createRoot)(host),handRef={current:null};// Drive the real component and renderer at the fixture's cadence, independent of software-GPU delays.
 const originalRAF=window.requestAnimationFrame,originalCancel=window.cancelAnimationFrame,originalNow=performance.now.bind(performance);let clock=originalNow(),rafId=0;const frames=new Map();window.requestAnimationFrame=callback=>{frames.set(++rafId,callback);return rafId;};window.cancelAnimationFrame=id=>frames.delete(id);performance.now=()=>clock;const advance=()=>{clock+=20;const queued=[...frames.values()];frames.clear();for(const callback of queued)callback(clock);};
 root.render((React.createElement||React.default.createElement)(LaunchMode,{handRef,color:'#4d9fff',mouseMode:false,cameraReady:true,videoRef:{current:{readyState:2,paused:false,ended:false}},onFailure:()=>{},onInteraction:()=>{}}));let sequence=0,hand=null;const wait=ms=>new Promise(r=>setTimeout(r,ms));
 const feed=async(pose,scale=1,x=0)=>{for(let n=0;n<4;n++){const points=pose.map(p=>({x:.5+(p.x-pose[0].x)*scale+x,y:.65+(p.y-pose[0].y)*scale,z:(p.z||0)*scale})),time=performance.now();hand=updateHand(hand,points,time,++sequence);hand.rawLandmarks=points;hand.sourceWidth=640;hand.sourceHeight=480;handRef.current=hand;advance();advance();}};
 try{await wait(350);host.querySelector('button').click();await wait(30);clock+=3100;advance();advance();await feed(poses.point);await feed(poses.point,1.2);const created=window.createdInstances;await feed(poses.open);await feed(poses.closed);const grabbed=handRef.current.grabDebug?.active;await feed(poses.closed,1,.1);const heldCount=window.createdInstances;await feed(poses.open,1,.1);const released=!handRef.current.grabDebug?.active;return {created,heldCount,grabbed,released};}finally{root.unmount();frames.clear();performance.now=originalNow;window.requestAnimationFrame=originalRAF;window.cancelAnimationFrame=originalCancel;host.remove();}
 },poses);expect(result.created).toBe(2);expect(result.heldCount).toBe(2);expect(result.grabbed).toBe(true);expect(result.released).toBe(true);
});

