import test from 'node:test';
import assert from 'node:assert/strict';
import {createChaosRuntime} from '../src/beyond/chaosRuntime.js';
const color='#ff354e',point={x:.5,y:.5};
const runtime=(options)=>{const r=createChaosRuntime(options);for(const m of ['GLOW','FLOW','SLASH','LAUNCH'])r.tick(m,0,true);return r;};
const record=(mode,id,kind={FLOW:'creation',SLASH:'destruction',LAUNCH:'hit'}[mode])=>({mode,id,kind,color,points:[point]});
test('preference validates blocked storage and preserves choice across clear',()=>{const r=runtime({storage:()=>{throw Error('blocked');}});assert.equal(r.preferenceIntensity(),'WILD');assert.equal(r.setIntensity('bad'),false);r.setIntensity('MAX');r.reset();assert.equal(r.preferenceIntensity(),'MAX');assert.equal(r.profile('LAUNCH').trails,16);assert.equal(r.profile('GLOW',true).moving,false);});
test('accepted unique events trigger active-time surge without banking',()=>{const r=runtime();r.tick('LAUNCH',0,true);for(let i=0;i<4;i++)r.accept(record('LAUNCH','hit'+i),{},0);assert.equal(r.snapshot('LAUNCH').state,'SURGE');r.accept(record('LAUNCH','extra'),{},1);r.tick('LAUNCH',6000,true);assert.equal(r.snapshot('LAUNCH').state,'COOLDOWN');assert.equal(r.snapshot('LAUNCH').meter,0);r.tick('LAUNCH',14000,true);assert.equal(r.snapshot('LAUNCH').state,'BUILDING');r.accept(record('LAUNCH','extra'),{},14000);assert.equal(r.snapshot('LAUNCH').meter,0);});
test('suspension freezes timers, clears decoration and rejects accumulation',()=>{const r=runtime();r.tick('FLOW',0,true);r.flowProgress('shape',1,0);r.accept(record('FLOW','done'),{},0);r.accept(record('FLOW','done2'),{},0);assert.equal(r.snapshot('FLOW').state,'SURGE');r.activity('FLOW',{point,color},0);r.setSuspended(true);assert.equal(r.counts().effects,0);r.tick('FLOW',20000,true);r.setSuspended(false);r.tick('FLOW',20000,true);r.tick('FLOW',25999,true);assert.equal(r.snapshot('FLOW').state,'SURGE');r.tick('FLOW',26000,true);assert.equal(r.snapshot('FLOW').state,'COOLDOWN');});
test('shape high water and throws are deduplicated independently of decoration',()=>{const r=runtime();r.flowProgress('shape',.5,0);r.flowProgress('shape',.2,0);r.flowProgress('shape',.5,0);assert.equal(r.snapshot('FLOW').meter,30);r.accept(record('LAUNCH','release','force'),{releaseId:'gesture',meaningful:true},0);r.accept(record('LAUNCH','release2','force'),{releaseId:'gesture',meaningful:true},0);assert.equal(r.snapshot('LAUNCH').meter,15);r.activity('FLOW',{point,color},0);assert.equal(r.snapshot('FLOW').meter,30);});
test('fresh meaningful movement requires displacement and respects rolling rate cap',()=>{const r=runtime();for(let t=0;t<1000;t+=100)r.presence({valid:true,moving:true,center:point,color,timestamp:t},t);assert.equal(r.snapshot('GLOW').meter,0);for(let t=1000;t<2000;t+=100)r.presence({valid:true,moving:true,center:{x:t%200===0?.3:.7,y:.5},color,timestamp:t},t);assert.equal(r.snapshot('GLOW').meter,12);r.presence({valid:true,moving:true,center:{x:.1,y:.5},color,timestamp:1000},3000);assert.equal(r.snapshot('GLOW').meter,12);});
test('caps expire and reduced motion draws no moving geometry',()=>{const r=runtime();r.setIntensity('MAX');for(let i=0;i<100;i++)r.activity('FLOW',{id:String(i),point,color,type:'strand'},0);assert.equal(r.counts().effects,48);assert.ok(r.counts().fluid<=4);let curves=0;const ctx={save(){},restore(){},beginPath(){},arc(){},stroke(){},moveTo(){},lineTo(){},quadraticCurveTo(){curves++;}};r.draw(ctx,100,100,100,'FLOW',true);assert.equal(curves,0);r.tick('FLOW',10000,true);assert.equal(r.counts().effects,0);r.replay('FLOW');assert.equal(r.snapshot('FLOW').meter,0);});

test('explicit paused or inactive mode cannot accumulate and inactivity freezes surge',()=>{const r=runtime();r.tick('LAUNCH',0,false);r.accept(record('LAUNCH','paused'),{},0);assert.equal(r.snapshot('LAUNCH').meter,0);r.tick('LAUNCH',1,true);for(let i=0;i<4;i++)r.accept(record('LAUNCH','active'+i),{},1);r.tick('LAUNCH',1001,true);r.tick('LAUNCH',1001,false);r.tick('LAUNCH',20000,false);r.tick('LAUNCH',20000,true);r.tick('LAUNCH',24999,true);assert.equal(r.snapshot('LAUNCH').state,'SURGE');r.tick('LAUNCH',25000,true);assert.equal(r.snapshot('LAUNCH').state,'COOLDOWN');});

test('surge onset produces one bounded effect and actual trails retain geometry',()=>{const r=runtime();for(let i=0;i<4;i++)r.accept(record('LAUNCH','h'+i),{},0);assert.equal(r.counts().effects,5);r.activity('LAUNCH',{point,color,type:'trail',points:[{x:.1,y:.2},{x:.8,y:.7}]},0);let moves=[],lines=[];const ctx={save(){},restore(){},beginPath(){},arc(){},stroke(){},moveTo(x,y){moves.push([x,y]);},lineTo(x,y){lines.push([x,y]);},quadraticCurveTo(){}};r.draw(ctx,100,100,100,'LAUNCH');assert.ok(moves.some(p=>p[0]===10&&p[1]===20));assert.ok(lines.some(p=>p[0]===80&&p[1]===70));});

test('combo bonus is earned once per crossing and resets only for a new chain',()=>{const r=runtime();r.accept(record('SLASH','one'),{combo:5},0);r.accept(record('SLASH','two'),{combo:5},0);assert.equal(r.snapshot('SLASH').meter,20);r.combo(0);r.accept(record('SLASH','three'),{combo:5},0);assert.equal(r.snapshot('SLASH').meter,32);});

test('pausing clears live decoration and inactive draw makes no moving marks',()=>{const r=runtime();r.activity('FLOW',{point,color,type:'strand'},0);assert.equal(r.counts().effects,1);r.tick('FLOW',10,false);assert.equal(r.counts().effects,0);let calls=0;const ctx=new Proxy({},{get:()=>()=>calls++});r.draw(ctx,100,100,20,'FLOW');assert.equal(calls,0);});

test('CLEAR cannot re-award previously accepted FLOW coverage',()=>{const r=runtime();r.flowProgress('same',.8,0);r.reset();r.tick('FLOW',1,true);r.flowProgress('same',.85,1,{point,color},.8);assert.equal(r.snapshot('FLOW').meter,3);});
