import test from 'node:test';
import assert from 'node:assert/strict';
import * as rules from '../src/game/slashArcade.js';
import {createSlashScene} from '../src/effects/slashScene.js';
import {createPersonalBests} from '../src/game/personalBests.js';
test('CHAOS density ramp preserves intervals but raises approved caps independently of presentation',()=>{ assert.equal(typeof rules.chaosSlashDifficulty,'function');for(const [s,c] of [[0,3],[30,6],[60,8],[90,10],[120,10]]){const d=rules.chaosSlashDifficulty(s/120);assert.equal(d.cap,c);assert.equal(d.interval,rules.slashArcadeDifficulty(s/120).interval);}assert.equal(rules.chaosSlashDifficulty(.5,true).cap,12); });
test('FRACTURE STORM triggers once per chain with four active seconds and eight-second cooldown',()=>{assert.equal(typeof rules.createFractureStorm,'function');const f=rules.createFractureStorm();assert.equal(f.update(9,0).active,false);assert.equal(f.update(10,1).active,true);assert.equal(f.update(20,4.999).active,true);assert.equal(f.update(20,5).active,false);f.update(0,6);assert.equal(f.update(10,7).active,false);assert.equal(f.update(20,20).active,false);f.update(0,21);assert.equal(f.update(10,22).active,true);f.reset();assert.equal(f.update(0,0).active,false);});
test('CHAOS bests preserve legacy SLASH records independently',()=>{const values=new Map(),b=createPersonalBests(()=>({getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)}));b.record('SLASH',{score:999,count:9},true);b.record('SLASH_CHAOS',{score:400,count:4},true);assert.equal(b.read('SLASH').score,999);assert.equal(b.read('SLASH_CHAOS').score,400);assert.ok(values.has('lumen.arcade.bests.v1.SLASH'));assert.ok(values.has('lumen.arcade.bests.chaos.v1.SLASH'));});
test('CHAOS formations stay atomically spaced and splitter reservations stay within twelve',()=>{const s=createSlashScene(null,{arcade:true,chaos:true,random:()=>.1});s.setSize(1200,800,{x:80,y:100,width:1040,height:580});for(let i=0;i<12;i++){s.update(.016,{phase:'playing',elapsed:100+i,interval:.28,cap:12,storm:true});const q=s.inspect();assert.ok(q.objects.length+q.reserved<=12);if(i===0){assert.ok(q.objects.length>=2);for(let a=0;a<q.objects.length;a++)for(let b=a+1;b<q.objects.length;b++){const x=q.objects[a],y=q.objects[b];assert.ok(Math.hypot(x.x-y.x,x.y-y.y)>=x.radius+y.radius+12);}}}assert.ok(s.inspect().objects.length>8);s.reset();assert.equal(s.inspect().objects.length,0);});
test('CHAOS destruction pool budgets adapt without changing crystal density',()=>{const s=createSlashScene(null,{chaos:true,arcade:true,random:()=>.5});s.setSize(1200,800,{x:0,y:0,width:1200,height:800});assert.equal(typeof s.setChaosProfile,'function');s.setChaosProfile({particles:96,fragments:12});for(let i=0;i<10;i++)s.update(.016,{phase:'playing',elapsed:100+i,interval:.28,cap:12});const before=s.inspect().objects.length;assert.ok(before>8);s.cut({start:{x:-100,y:650},end:{x:1400,y:650},edge:[{x:1400,y:0},{x:1400,y:800}],previousEdge:[{x:-100,y:0},{x:-100,y:800}],strength:1,robust:true});const e=s.inspect().effects;assert.ok(e.particles<=96);assert.ok(e.fragments<=12);assert.ok(e.flashes<=12);s.setChaosProfile({particles:320,fragments:48});s.reset();assert.equal(s.inspect().effects.particles,0);});

test('CHAOS splitter children retain two independent rewards and separated reachable geometry',()=>{const events=[],s=createSlashScene(null,{arcade:true,chaos:true,random:()=>.1,onLifecycle:e=>events.push(e)});s.setSize(1000,700,{x:30,y:80,width:940,height:500});s.update(.016,{phase:'playing',elapsed:20,interval:.28,cap:10});const p=s.inspect().objects.find(o=>o.type==='splitting');assert.ok(p);s.cut({start:{x:p.x-10,y:p.y},end:{x:p.x+10,y:p.y},edge:[{x:p.x+10,y:p.y-2},{x:p.x+10,y:p.y+2}],previousEdge:[{x:p.x-10,y:p.y-2},{x:p.x-10,y:p.y+2}],strength:1});const children=s.inspect().objects.filter(o=>o.type==='child');assert.equal(children.length,2);assert.equal(children[0].points,100);assert.equal(children[0].radius,Math.max(20,p.radius*.65));for(const c of children){assert.ok(c.x-c.radius>=30&&c.x+c.radius<=970&&c.y-c.radius>=80&&c.y+c.radius<=580);}assert.ok(Math.hypot(children[0].x-children[1].x,children[0].y-children[1].y)>=children[0].radius+children[1].radius+12);assert.equal(s.inspect().reserved,0);});

test('clearing presentation preserves scoring objects and cannot refire a current combo chain',()=>{const f=rules.createFractureStorm();f.update(10,1);f.reset(10);assert.equal(f.update(10,2).active,false);const s=createSlashScene(null,{chaos:true,arcade:true,random:()=>.5});s.setSize(1000,700,{x:0,y:0,width:1000,height:700});s.update(.016,{phase:'playing',elapsed:20,cap:10,interval:.28});const ids=s.inspect().objects.map(o=>o.id);assert.equal(typeof s.clearEffects,'function');s.clearEffects();assert.deepEqual(s.inspect().objects.map(o=>o.id),ids);assert.equal(s.inspect().effects.particles,0);});
