import test from 'node:test';
import assert from 'node:assert/strict';
import {createEchoStore} from '../src/echoes/echoStore.js';
import {createEchoPath} from '../src/echoes/echoGeometry.js';
import {drawEchoComposition,galleryEchoRecords} from '../src/echoes/echoComposition.js';
const event=(id,mode='FLOW')=>({id,mode,kind:'creation',color:'#b06aff',points:[{x:.1,y:.2},{x:.3,y:.4}],intensity:.7});
test('store sanitizes private fields and isolates snapshots',()=>{const s=createEchoStore();const e=s.append({...event('a'),landmarks:[1],points:[{x:-1,y:2},{x:.333333,y:.5}]});assert.equal(e.points[0].x,0);assert.equal(e.points[0].y,1);assert.equal(e.points[1].x,Math.round(.333333*1024)/1024);assert.equal('landmarks' in e,false);s.snapshot()[0].points[0].x=1;assert.equal(s.snapshot()[0].points[0].x,0);assert.equal(s.append(event('a')),null);assert.equal(s.append({...event('b'),color:'#ffffff'}),null);});
test('store evicts per mode and rejects callbacks from a cleared epoch',()=>{const s=createEchoStore();let n=0;const stop=s.subscribe(()=>n++);for(let i=0;i<100;i++)s.append(event(String(i)));assert.equal(s.snapshot().length,64);assert.equal(s.snapshot()[0].id,'36');const epoch=s.epoch;s.clear();assert.equal(s.append(event('stale'),epoch),null);assert.equal(s.snapshot().length,0);stop();s.append(event('new'));assert.equal(n,101);});
test('scratch paths preserve interruptions and remain bounded',()=>{const p=createEchoPath(8);p.sample({active:true,x:.1,y:.1,source:'hand',sequence:1,timestamp:0});p.sample({active:true,x:.15,y:.1,source:'hand',sequence:2,timestamp:20});p.sample({active:true,x:.16,y:.1,source:'hand',sequence:2,timestamp:20});p.sample({active:true,x:.2,y:.1,source:'hand',sequence:3,timestamp:400});assert.equal(p.points().length,3);assert.equal(p.points()[2].break,true);for(let i=4;i<100;i++)p.sample({active:true,x:.2+i/1000,y:.1,source:'hand',sequence:i,timestamp:400+i*10});assert.ok(p.points().length<=8);p.clear();assert.equal(p.points().length,0);});
test('composition deterministically draws actual path coordinates without randomness',()=>{const draw=()=>{const calls=[];const c=new Proxy({},{get:(_,key)=>key==='createRadialGradient'?()=>({addColorStop(){}}):(...args)=>calls.push([key,...args]),set:(_,key,value)=>{calls.push([key,value]);return true;}});drawEchoComposition(c,[event('a')],100,100);return calls;};assert.deepEqual(draw(),draw());assert.ok(draw().some(c=>c[0]==='lineTo'));});

test('all modes retain at most256 records and64 points with sub-MiB serialized payload',()=>{const store=createEchoStore();const kinds={GLOW:'presence',FLOW:'creation',SLASH:'destruction',LAUNCH:'hit'};for(const mode of Object.keys(kinds))for(let i=0;i<100;i++)store.append({id:mode+i,mode,kind:kinds[mode],color:'#b06aff',points:Array.from({length:256},(_,n)=>({x:n/255,y:n/256})),intensity:1});const records=store.snapshot();assert.equal(records.length,256);for(const mode of Object.keys(kinds))assert.equal(records.filter(r=>r.mode===mode).length,64);assert.ok(records.every(r=>r.points.length<=64));assert.ok(Buffer.byteLength(JSON.stringify(records))<1024*1024);});

test('gallery preserves physical geometry proportions across source viewports',()=>{const mapped=galleryEchoRecords([{aspect:2,points:[{x:.4,y:.3},{x:.6,y:.7}]}])[0].points;assert.ok(Math.abs((mapped[1].x-mapped[0].x)-(mapped[1].y-mapped[0].y))<1e-8);});
