import test from 'node:test';
import assert from 'node:assert/strict';
import {createPulseDetector,buildPulseHandInput} from '../src/tracking/pulseDetector.js';
const frame=(t,open=false)=>({active:true,timestamp:t,sequence:t,neutral:!open,open,center:{x:.5,y:.5},scale:.1});
function arm(d,start=0){for(let t=start;t<=start+200;t+=50)d.update(frame(t),t);}
test('neutral then stable fresh open hold triggers once',()=>{const d=createPulseDetector();arm(d);let out;for(let t=250;t<=1450;t+=50)out=d.update(frame(t,true),t);assert.equal(out.triggered,true);assert.equal(d.update(frame(1500,true),1500).triggered,false);});
test('repeated frames, stale observations, gaps and unstable holds cannot trigger',()=>{const d=createPulseDetector();arm(d);d.update(frame(250,true),250);assert.equal(d.update(frame(250,true),1450).triggered,false);assert.equal(d.update(frame(1500,true),1500).state,'WAIT_NEUTRAL');arm(d,1600);for(let t=1850;t<3200;t+=50){const f=frame(t,true);f.center.x=t===2000?.6:.5;assert.equal(d.update(f,t).triggered,false);}});
test('blocked and reset require fresh neutral; cooldown requires release',()=>{const d=createPulseDetector();arm(d);assert.equal(d.update({...frame(250,true),blocked:true},250).state,'WAIT_NEUTRAL');for(let t=300;t<1800;t+=50)assert.equal(d.update(frame(t,true),t).triggered,false);d.reset();assert.equal(d.update(frame(2000,true),2000).triggered,false);assert.equal(buildPulseHandInput(null,true).active,false);});
test('hand adapter uses tracked handDetected and all four open fingers',()=>{const landmarks=Array.from({length:21},(_,i)=>({x:.4+(i%4)*.01,y:.6-i*.01,z:0}));const result=buildPulseHandInput({handDetected:true,landmarks,timestamp:20,sequence:1});assert.equal(result.active,true);assert.equal(result.timestamp,20);});
test('cooldown and neutral release both gate a second pulse',()=>{const d=createPulseDetector();arm(d);for(let t=250;t<=1450;t+=50)d.update(frame(t,true),t);for(let t=1500;t<=4500;t+=50)assert.equal(d.update(frame(t,true),t).triggered,false);arm(d,4550);let out;for(let t=4800;t<=6000;t+=50)out=d.update(frame(t,true),t);assert.equal(out.triggered,true);});
test('FIRED is visible once then waits for neutral',()=>{const d=createPulseDetector();arm(d);let out;for(let t=250;t<=1450;t+=50)out=d.update(frame(t,true),t);assert.equal(out.state,'FIRED');assert.equal(d.update(frame(1500,true),1500).state,'WAIT_NEUTRAL');});
